# Configuration for actions/labeler
# Auto-labels PRs based on changed files
# Note: This is for the meta-repository. Component repos have their own configs.

# Documentation
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "**/*.md"
          - "!.github/**/*.md"

# CI/CD and GitHub configuration
area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "!.github/maintenance/**"

# Kubernetes/Helm
area/k8s:
  - changed-files:
      - any-glob-to-any-file:
          - "k8s/**"
          - "helm/**"
          - "**/*k8s*"
          - "**/*kubernetes*"

# Docker
area/docker:
  - changed-files:
      - any-glob-to-any-file:
          - "Dockerfile*"
          - "docker/**"
          - "docker-compose*.yml"
          - ".dockerignore"

# Terraform
area/terraform:
  - changed-files:
      - any-glob-to-any-file:
          - "terraform/**"
          - "terraform-provider-inferadb/**"
          - "**/*.tf"

# Configuration files
area/config:
  - changed-files:
      - any-glob-to-any-file:
          - "config*.yaml"
          - "config*.yml"
          - "**/*.toml"
          - "!**/Cargo.toml"
          - "!**/rust-toolchain.toml"
          - "!**/deny.toml"

# Rust dependencies
area/deps:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Cargo.toml"
          - "**/Cargo.lock"
          - "**/deny.toml"

# Testing infrastructure
area/testing:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"
          - "**/tests/**"
          - "**/*_test.rs"
          - "**/*_tests.rs"
          - "**/*test-fixtures*/**"

# Observability (metrics, logging, tracing)
area/observability:
  - changed-files:
      - any-glob-to-any-file:
          - "grafana/**"
          - "prometheus/**"
          - "**/*observe*/**"
          - "**/*telemetry*/**"
          - "**/*metrics*"
          - "**/*tracing*"

# Engine component (when working in submodule)
repo/engine:
  - changed-files:
      - any-glob-to-any-file:
          - "engine/**"

# Control component (when working in submodule)
repo/control:
  - changed-files:
      - any-glob-to-any-file:
          - "control/**"

# Dashboard component (when working in submodule)
repo/dashboard:
  - changed-files:
      - any-glob-to-any-file:
          - "dashboard/**"

# CLI component (when working in submodule)
repo/cli:
  - changed-files:
      - any-glob-to-any-file:
          - "cli/**"

# Tests component (when working in submodule)
repo/tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"
